/*
 * SPI_config.h
 *
 * Created: 10/30/2023 12:23:59 PM
 *  Author: Hassan Said
 */ 


#ifndef SPI_CONFIG_H_
#define SPI_CONFIG_H_

/*
* Choose from:
* SPI_SPEED_MODE_NORMAL
* SPI_SPEED_MODE_DOUBLE
*/

#define SPI_SPEED_MODE SPI_SPEED_MODE_NORMAL

/*
* Choose from:
* Normal speed:
* SPI_PRESCALER_NORAML_4
* SPI_PRESCALER_NORAML_16
* SPI_PRESCALER_NORAML_64
* SPI_PRESCALER_NORAML_128
*
* Double speed:
* SPI_PRESCALER_DOUBLE_2
* SPI_PRESCALER_DOUBLE_8
* SPI_PRESCALER_DOUBLE_32
* SPI_PRESCALER_DOUBLE_64
*/

#define SPI_PRESCALER SPI_PRESCALER_NORAML_16

/*
* Choose from:
* SPI_CLK_POL_IDLE_HIGH
* SPI_CLK_POL_IDLE_LOW
*/

#define SPI_CLK_POL SPI_CLK_POL_IDLE_LOW

/*
* Choose from:
* SPI_CLK_PHASE_SAMPLE_FIRST
* SPI_CLK_PHASE_SAMPLE_FIRST
*/

#define SPI_CLK_PHASE SPI_CLK_PHASE_SAMPLE_FIRST

/*
* Choose from:
* SPI_DATA_ORDER_MSB_FIRST
* SPI_DATA_ORDER_LSB_FIRST
*/

#define SPI_DATA_ORDER SPI_DATA_ORDER_LSB_FIRST


#endif /* SPI_CONFIG_H_ */