/*
 * TIMER0_config.h
 *
 * Created: 10/24/2023 9:26:43 AM
 *  Author: Hassan Said
 */ 


#ifndef TIMER0_CONFIG_H_
#define TIMER0_CONFIG_H_

/*
*  Choose from:
*  TIMER0_MODE_NORMAL
*  TIMER0_MODE_CTC
*  TIMER0_MODE_FAST_PWM
*  TIMER0_MODE_PHASECORRECT_PWM
*/

#define TIMER0_MODE TIMER0_MODE_FAST_PWM

/*
*  Choose from:
*  TIMER0_PRESCALER_1
*  TIMER0_PRESCALER_8
*  TIMER0_PRESCALER_64
*  TIMER0_PRESCALER_256
*  TIMER0_PRESCALER_1024
*  TIMER0_PRESCALER_EXT_FALLING_EDGE
*  TIMER0_PRESCALER_EXT_RISING_EDGE
*/

#define TIMER0_PRESCALER TIMER0_PRESCALER_64


/*
*  Choose from:
*  Non PWM:
*  TIMER0_OC0_MODE_DISCONNECTED
*  TIMER0_OC0_MODE_TOG
*  TIMER0_OC0_MODE_SET
*  TIMER0_OC0_MODE_CLR 
*
*  PWM:
*  TIMER0_OC0_MODE_PWM_INVERTED
*  TIMER0_OC0_MODE_PWM_NONINVERTED
*/

#define TIMER0_OC0_MODE TIMER0_OC0_MODE_PWM_NONINVERTED

# define FCPU 16UL 


#endif /* TIMER0_CONFIG_H_ */
